### PR TITLE
Added Comments and share

### PR DESCRIPTION
**Pull request by Rohanmond**
- user can comment on a particular post
- user can reply on a particular comment
- user can edit delete (if the comment belongs to his/her ) or upvote a particular comment
- added share post functionalities
- user can delete comment of any user if the post is belongs to his/her
https://socially-5ye74u9ut-rohanmond.vercel.app/

### CODE REVIEW

**Review by romabulani — APPROVED** [review]
- All functiomalities are working as expected
- Check the copy link as it is giving the localhost link
- Rest all looks good to merge

**Review by ScoobyDubeyDo — APPROVED** [review]
Nice ui 
Good file structure followed

**Review by anuj-kumary — APPROVED** [review]
Clean Code and good folder structure
Functionalities are working as expected
Good to merge

**Review by ramalingaa — APPROVED** [review]
Clean code, good folder structure. Looks good to merge

**Pull request merged**
